name: 'Query Issues'
description: 'Query issues from the specified owner/repo'
inputs:
  token:
    description: 'github token to be used to access github API'
    required: true
    default: 'undefined'
  repo:
    description: 'repo to query issues ( =owner/repo_name )'
    required: true
    default: 'undefined/undefined'
  author:
    description: '[optional] query issues created by author'
    required: false
    default: ''
  state:
    description: '[optional] query issues that are in state'
    required: false
    default: 'OPEN'
  output_json:
    description: '[out] a file to store the issues in json format'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.author }}
    - ${{ inputs.state }}
    - ${{ inputs.output_json }}
