name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: use action
        id: my-action
        uses: jrdeng/query-issues-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: jrdeng/jrdeng.github.io
          author: jrdeng

      - name: check output
        run: |
          echo ${{ steps.my-action.outputs.error_msg }}
          echo ${{ steps.my-action.outputs.issue_list }} > issues.json
          pwd
          ls
