name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: use action
        id: my-action
        uses: jrdeng/query-issues-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: jrdeng/jrdeng.github.io
          author: jrdeng
          output_json: ./issues.json

      - name: check output
        run: |
          pwd
          ls -l
          cat ./issues.json
